#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Fri May  3 21:58:23 2013

import wx

# begin wxGlade: extracode
import wx.lib.mixins.listctrl as listmix

class EditableListCtrl(wx.ListCtrl, listmix.TextEditMixin):
    ''' TextEditMixin allows any column to be edited. '''
 
    #----------------------------------------------------------------------
    def __init__(self, parent, ID=wx.ID_ANY, pos=wx.DefaultPosition,
                 size=wx.DefaultSize, style=0):
        """Constructor"""
        wx.ListCtrl.__init__(self, parent, ID, pos, size, style)
        listmix.TextEditMixin.__init__(self)
# end wxGlade


class GladeFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GladeFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.stock_id_ctrl = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER | wx.TE_PROCESS_TAB | wx.TE_MULTILINE)
        self.sizer_4_staticbox = wx.StaticBox(self, -1, "Stock ID")
        self.stat_item_list = EditableListCtrl(self, -1, style=wx.LC_REPORT | wx.LC_EDIT_LABELS | wx.LC_HRULES | wx.LC_VRULES | wx.SUNKEN_BORDER)
        self.add_button = wx.Button(self, -1, "Add")
        self.del_button = wx.Button(self, -1, "Delete")
        self.sizer_3_staticbox = wx.StaticBox(self, -1, "Statistic Items")
        self.save_button = wx.Button(self, -1, "Save")
        self.run_button = wx.Button(self, -1, "Run!")
        self.sizer_2_staticbox = wx.StaticBox(self, -1, "Crawler Config")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GladeFrame.__set_properties
        self.SetTitle("Sina Finance Crawler")
        self.SetSize((671, 400))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GladeFrame.__do_layout
        self.sizer_2_staticbox.Lower()
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 3, 3)
        self.sizer_3_staticbox.Lower()
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_4_staticbox.Lower()
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
        sizer_4.Add(self.stock_id_ctrl, 0, wx.EXPAND, 3)
        grid_sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add(self.stat_item_list, 1, wx.ALL | wx.EXPAND, 3)
        sizer_5.Add(self.add_button, 0, 0, 0)
        sizer_5.Add(self.del_button, 0, 0, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.save_button, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.run_button, 0, wx.EXPAND, 0)
        grid_sizer_1.AddGrowableRow(0)
        grid_sizer_1.AddGrowableCol(0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

# end of class GladeFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    MF = GladeFrame(None, -1, "")
    app.SetTopWindow(MF)
    MF.Show()
    app.MainLoop()
